#!/bin/bash

# Uptime Kuma Monitor Setup Script
# This script provides instructions for setting up monitors in Uptime Kuma

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         Uptime Kuma Monitor Setup Instructions              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Access Uptime Kuma:"
echo "   URL: http://31.97.222.218:3001"
echo "   (Access from your local machine or setup SSH tunnel)"
echo ""
echo "🔧 SSH Tunnel Command (if needed):"
echo "   ssh -L 3001:localhost:3001 root@31.97.222.218"
echo "   Then access: http://localhost:3001"
echo ""
echo "📋 Monitors to Add:"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "CRITICAL WEB SERVICES (HTTP/HTTPS)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. n8n Automation"
echo "   Type: HTTP(s)"
echo "   URL: https://n8n.theprofitplatform.com.au"
echo "   Interval: 60 seconds"
echo "   Retries: 3"
echo ""
echo "2. Main Website"
echo "   Type: HTTP(s)"
echo "   URL: https://theprofitplatform.com.au"
echo "   Interval: 60 seconds"
echo "   Retries: 3"
echo ""
echo "3. Coolify Dashboard"
echo "   Type: HTTP(s)"
echo "   URL: https://coolify.theprofitplatform.com.au"
echo "   Interval: 60 seconds"
echo "   Retries: 3"
echo ""
echo "4. SEO Dashboard"
echo "   Type: HTTP(s)"
echo "   URL: http://localhost:9000/api/v2/health"
echo "   Interval: 120 seconds"
echo "   Retries: 2"
echo ""
echo "5. Repair Frontend"
echo "   Type: HTTP(s)"
echo "   URL: http://localhost:3000"
echo "   Interval: 120 seconds"
echo "   Retries: 2"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "DATABASES & CACHES (TCP Port)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "6. PostgreSQL (Main)"
echo "   Type: Port"
echo "   Hostname: localhost"
echo "   Port: 5432"
echo "   Interval: 300 seconds"
echo ""
echo "7. PostgreSQL (Repair)"
echo "   Type: Port"
echo "   Hostname: localhost"
echo "   Port: 5433"
echo "   Interval: 300 seconds"
echo ""
echo "8. Redis"
echo "   Type: Port"
echo "   Hostname: localhost"
echo "   Port: 6379"
echo "   Interval: 300 seconds"
echo ""
echo "9. Qdrant Vector DB"
echo "   Type: HTTP(s)"
echo "   URL: https://qdrant.theprofitplatform.com.au"
echo "   Interval: 300 seconds"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "SERVICES"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "10. Jenkins"
echo "    Type: HTTP(s)"
echo "    URL: http://localhost:8080"
echo "    Interval: 300 seconds"
echo ""
echo "11. FileBrowser"
echo "    Type: HTTP(s)"
echo "    URL: http://localhost:8084"
echo "    Interval: 300 seconds"
echo ""
echo "12. AnythingLLM"
echo "    Type: HTTP(s)"
echo "    URL: http://localhost:3005"
echo "    Interval: 300 seconds"
echo ""
echo "13. Glitchtip"
echo "    Type: HTTP(s)"
echo "    URL: http://localhost:8001"
echo "    Interval: 300 seconds"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "DOCKER CONTAINERS (Docker Health)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "14-16. GitHub Runners"
echo "    Type: Docker Container"
echo "    Containers:"
echo "      - runner-1-vs4o4ogkcgwgwo8kgksg4koo"
echo "      - runner-5-vs4o4ogkcgwgwo8kgksg4koo"
echo "      - runner-automation-vs4o4ogkcgwgwo8kgksg4koo"
echo "    Interval: 120 seconds"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "NOTIFICATION SETUP"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Recommended notification channels:"
echo "  • Email (for critical alerts)"
echo "  • Discord/Slack (for real-time notifications)"
echo "  • Webhook (for custom integrations)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ After setup, you'll have complete visibility of all services!"
echo ""
